import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from "../styles/objects/projects/_article.module.scss"
import { Header } from '@/components/layouts/Header'
import { client } from '@/libs/client'
import { Footer } from '@/components/layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ articles }) {
  return (
    <>
      <Head>
        <title>HOME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='min-h-screen px-5 pb-24 bg-teal-200'>
        <section>
          <ul className='grid gap-y-12 mx-auto max-w-4xl'>
            {
            articles.map(article => {
              const date = article.date.slice(0, 10);
              const datetime = date.replaceAll('-', '/');
              const tags = [...article.tags].map(tag => (
                <li key={tag.name} style={{'--theme': (tag.color || '#1f2937')}}>{tag.name}</li>
              ), null);
              return (
                <li key={article.id}>
                  <Link
                    href={`/article/${article.id}/`}
                    className='grid grid-cols-articles gap-x-5 p-5 bg-white rounded-xl shadow-xl'
                  >
                    <figure className='pt-75 relative'>
                      <Image
                        className='rounded object-center object-cover'
                        src={article.thumbnail || 'https://images.microcms-assets.io/assets/65e3774d54b3483f8ebaab32e063620e/7b623a431dc94c73b21629d88aab0874/noimage.jpg'}
                        alt=''
                        fill
                      />
                    </figure>
                    <div className='flex flex-col justify-between pt-2 pb-1'>
                      <h3 className='grid gap-y-2 justify-items-start text-xl'>
                        <span className='grid gap-x-2 items-center'>
                          <time dateTime={date} className={`${styles['c-datetag']} 'col-auto'`}>{datetime}</time>
                          <span className='col-start-2 text-sm'>{article.author.name}</span>
                        </span>
                        {article.title}
                      </h3>
                      <ul className={styles['c-article-tags']}>{tags}</ul>
                    </div>
                  </Link>
                </li>
              )
            })
            }
          </ul>
        </section>
        {/* <div>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div>
          <Image
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
      <Footer />
    </>
  )
}

// データをテンプレートに受け渡す部分の処理を記述します
export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "article" });
  return {
    props: {
      articles: data.contents,
    },
  };
};
